apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-command-injection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server-command-injection
  template:
    metadata:
      labels:
        app: web-server-command-injection
    spec:
      containers:
        - name: web-server-command-injection
          image: ghcr.io/kube-hack/command-injection:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /go/templates
              name: templates
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: templates
          configMap:
            name: html-templates-command-injection

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: html-templates-command-injection
data:
{{ (.Files.Glob "files/templates/*").AsConfig | indent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: web-server-command-injection
  labels:
    app: web-server-command-injection
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 8080
  selector:
    app: web-server-command-injection